"""Task decomposition.

The planner asks the local model for a strict JSON plan; if that fails,
it falls back to a single deterministic subtask so the rest of the agent
can still make progress.
"""

from __future__ import annotations

from dataclasses import dataclass

from ..llm.client import ChatMessage, LLMClient, LLMError
from ..prompting.schemas import Plan, Subtask, parse_plan
from ..prompting.templates import task_decomposition_prompt


@dataclass
class PlannerResult:
    plan: Plan
    fallback_used: bool


def fallback_plan(task: str) -> Plan:
    """Build a single-subtask plan from the user request alone."""
    return Plan(
        task=task,
        assumptions=[],
        subtasks=[
            Subtask(
                id="T1",
                goal=task,
                reason="Fallback single-subtask plan (model produced no valid plan).",
                search_queries=[],
                likely_files=[],
                edit_scope="small",
                validation="",
                needs_external_docs=False,
                external_doc_reason="",
            )
        ],
        stop_conditions=["Validation passes."],
        risks=["Plan was generated by fallback heuristic."],
    )


def make_plan(
    task: str,
    repo_summary_text: str,
    *,
    llm: LLMClient | None = None,
) -> PlannerResult:
    """Ask the model for a JSON plan, falling back to a single subtask."""
    if llm is None:
        return PlannerResult(plan=fallback_plan(task), fallback_used=True)

    prompt = task_decomposition_prompt(task, repo_summary_text)
    try:
        result = llm.chat(
            [
                ChatMessage(
                    role="system",
                    content=(
                        "You are a planner for a small-context coding agent. "
                        "Always respond with valid JSON only."
                    ),
                ),
                ChatMessage(role="user", content=prompt),
            ],
            temperature=0.0,
            max_tokens=600,
        )
    except LLMError:
        return PlannerResult(plan=fallback_plan(task), fallback_used=True)

    plan = parse_plan(result.text)
    if plan is None or not plan.subtasks:
        return PlannerResult(plan=fallback_plan(task), fallback_used=True)
    return PlannerResult(plan=plan, fallback_used=False)
